version: '2.4'
services:
    phamduy:
        build: .
        ## roswellにモデルを置くためにマウントする場合
        volumes:
            - /home/itolab/temp/toxic-comment-classification-challenge:/usr/src/
        ## runtimeを指定する！！
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        command: nvidia-smi